name: Text2SQL -  Docker CI/CD Pipeline
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    
    - name: Build Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: false
        load: true
        tags: text2sql-app:latest
    
    - name: Run tests in Docker
      run: docker run --rm text2sql-app:latest python -m unittest test.py
      env:
        GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
    
    - name: Run main script in Docker
      run: docker run --rm -e GOOGLE_API_KEY=${{ secrets.GOOGLE_API_KEY }} text2sql-app:latest python main.py
    
    - name: Run app script in Docker
      run: docker run --rm -e GOOGLE_API_KEY=${{ secrets.GOOGLE_API_KEY }} text2sql-app:latest python app.py
